### ISSUE TITLE
Issue gmaven-plugin release please with gmaven 2

### ISSUE THREAD

**Issue by milanaleksic** [groovy/gmaven#5]
Hi, I have encountered a GMAVEN-87 bug referenced for example by https://stackoverflow.com/questions/9870047/maven-3-parallel-gmaven-sporadic-failure which blocks parallel builds when we use gmaven-plugin. I understand that there are some commits in this project (gmaven) that should help remedy the situation and that those fixes should be included in gmaven 2.

But, as I can see there was never a new release of gmaven-plugin, at least not that I can find in maven central. So, could you please think about including and releasing gmaven-plugin version 2.0 (and of course make sure it works as gmaven 2) that would use gmaven 2?

I understand of course that this should be an issue in `gmaven-plugin` project and not in this, but I couldn't find that project in this GitHub Groovy organization account.

**Comment by jdillon** [comment]
Will have a look, since the move of things to Apache and the disappearance of Codehaus, releases were put on pause, but will try and get it sorted out.

**Comment by jdillon** [comment]
I think I now have perms to deploy this, need to adjust a few things but will happen soon.

**Comment by jdillon** [comment]
first step, testing basic deployment, have 2.1-SNAPSHOT deployed: https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/gmaven/gmaven/2.1-SNAPSHOT/

the site stuff is a bit of mess with the updates, but will get to that soon.  also the plumbing for maven has changed a lot since this was last released, so I may put out a release first then update that to bring it back up to sanity.

**Comment by jdillon** [comment]
so latest 2.1-SNAPSHOT should resolve this, if you can confirm that would be helpful.  for now closing, re-open if its not fixed.

**Comment by jdillon** [comment]
http://repo1.maven.org/maven2/org/codehaus/gmaven/groovy-maven-plugin/2.1/
